//Brows UI Actions
export const BROWSE_SAVE_LIKE = 'BROWSE_SAVE_LIKE';
export const BROWSE_SAVE_HATE = 'BROWSE_SAVE_HATE';
export const BROWSE_REQUEST_POSTINGS = 'BROWSE_REQUEST_POSTINGS';
export const BROWSE_REQUEST_POSTINGS_ERROR = 'BROWSE_REQUEST_POSTINGS_ERROR';
export const BROWSE_RECEIVE_POSTINGS = 'BROWSE_RECEIVE_POSTINGS';
export const BROWSE_GET_POSTING = 'BROWSE_GET_POSTING';

//Search UI Actions
export const SEARCH_SET_PARAMETERS = 'SEARCH_SET_PARAMETERS';
export const SEARCH_REQUEST_POSTINGS = 'SEARCH_REQUEST_POSTINGS';
export const SEARCH_REQUEST_POSTINGS_ERROR = 'SEARCH_REQUEST_POSTINGS_ERROR';
export const SEARCH_RECEIVE_POSTINGS = 'SEARCH_RECEIVE_POSTINGS';