//Brows UI Actions
export const BROWSE_SAVE_LIKE = 'BROWSE_SAVE_LIKE';
export const BROWSE_DELETE_LIKE = 'BROWSE_DELETE_LIKE';
export const BROWSE_SAVE_HATE = 'BROWSE_SAVE_HATE';
export const REQUEST_LISTING_DETAILS = 'REQUEST_LISTING_DETAILS';
export const RECEIVE_LISTING_DETAILS = 'RECEIVE_LISTING_DETAILS';
export const CORE_ERROR = 'CORE_ERROR';
export const CLEAR_SELECTED_LISTING = 'CLEAR_SELECTED_LISTING';
//Search UI Actions
export const SEARCH_SET_PARAMETERS = 'SEARCH_SET_PARAMETERS';
export const SEARCH_REQUEST_POSTINGS = 'SEARCH_REQUEST_POSTINGS';
export const SEARCH_REQUEST_POSTINGS_ERROR = 'SEARCH_REQUEST_POSTINGS_ERROR';
export const SEARCH_RECEIVE_POSTINGS = 'SEARCH_RECEIVE_POSTINGS';
export const SEARCH_RESET_QUERY = 'SEARCH_RESET_QUERY';
